### ISSUE TITLE
WARNING: Method definition `boundscheck` is overwritten 

### ISSUE THREAD

**Issue by prbzrg** [JuliaSIMD/StrideArraysCore.jl#17]
I got this warning: 
```julia
WARNING: Method definition boundscheck() in module StrideArraysCore at C:\Users\Hossein Pourbozorg\.julia\packages\StrideArraysCore\pjIfM\src\ptr_array.jl:512 overwritten at C:\Users\Hossein Pourbozorg\.julia\packages\StrideArraysCore\pjIfM\src\StrideArraysCore.jl:54.
```

**Comment by chriselrod** [comment]
Did you start Julia with `--check-bounds=yes`?

**Comment by prbzrg** [comment]
Yes, I did.

**Comment by chriselrod** [comment]
It disables bounds checking by default:
https://github.com/JuliaSIMD/StrideArraysCore.jl#caution
So it's letting you know what it is enabling them when you start Julia with forced bounds checking.

There is a ton of code that doesn't use `@inbuonds` because "there's no guarantee people implemented their array types correctly", meaning checking axes isn't enough to guarantee `@inbounds` is safe.
There were several benchmarks negatively impacted by this.

I didn't want to reimplement all of these functions, so instead I turned bounds checks off by default, but let people manually turn them on by redefining the `StrideArraysCore.boundscheck` function.

If you start Julia with `--check-bounds=yes`, it'll redefine it for you to turn bounds checks on.

**Comment by prbzrg** [comment]
I didn't know that. Thanks for response
